"""update letter

Revision ID: b63aee4da173
Revises: bdec54e9d418
Create Date: 2025-12-16 18:25:55.582406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63aee4da173'
down_revision: Union[str, Sequence[str], None] = 'bdec54e9d418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letters', 'ornament_shape',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('letters', 'ornament_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('letters', 'ornament_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('letters', 'ornament_shape',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
