"""update letter

Revision ID: bdec54e9d418
Revises: a066306f6196
Create Date: 2025-12-16 12:37:09.061793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdec54e9d418'
down_revision: Union[str, Sequence[str], None] = 'a066306f6196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('ornament_shape', sa.String(length=20), nullable=True))
    op.add_column('letters', sa.Column('ornament_color', sa.String(length=20), nullable=True))
    op.add_column('letters', sa.Column('is_event_ornament', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('letters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_letters_user_id_created_at', 'letters', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_user_letter_number', 'letters', ['user_id', 'letter_number'])
    op.drop_column('letters', 'ornament_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('ornament_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_letter_number', 'letters', type_='unique')
    op.drop_index('idx_letters_user_id_created_at', table_name='letters')
    op.alter_column('letters', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('letters', 'is_event_ornament')
    op.drop_column('letters', 'ornament_color')
    op.drop_column('letters', 'ornament_shape')
    # ### end Alembic commands ###
